language: scala

scala:
  - 2.10.6
  - 2.11.8

jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot

install:
  - pip install --user codecov

script:
  - if [[ "$TRAVIS_JDK_VERSION" == *jdk8* ]] && [[ "$TRAVIS_SCALA_VERSION" == 2.11.* ]];
      then
        sbt ++$TRAVIS_SCALA_VERSION clean validateJVM coverage coverageReport;
        sbt ++$TRAVIS_SCALA_VERSION coverageAggregate;
        codecov;
        sbt ++$TRAVIS_SCALA_VERSION clean validateJS;
      else
        sbt ++$TRAVIS_SCALA_VERSION clean core/test tests/test monix/test scalaz/test twitter/test;
        sbt ++$TRAVIS_SCALA_VERSION monix/it:test scalaz/it:test twitter/it:test;
    fi;

  # See http://www.scala-sbt.org/0.13/docs/Travis-CI-with-sbt.html
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
